services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.app
    env_file:
      - .env
    environment:
      - APP_HTTP_ADDR=:8080
      - MIGRATE=1
      - MIGRATE_DIR=/migrations
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - appnet

  caddy:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app
    networks:
      - appnet

  db:
    image: postgres:16-alpine
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - appnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 2s
      timeout: 5s
      retries: 10

  n8n:
    image: n8nio/n8n
    restart: unless-stopped
    environment:
      - N8N_HOST=n8n.gmcl.co.uk
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://n8n.gmcl.co.uk/
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
    env_file:
      - .env
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  db_data:
  caddy_data:
  caddy_config:
  n8n_data:
