CREATE TABLE IF NOT EXISTS umpires (
    id BIGSERIAL PRIMARY KEY,
    forename TEXT NOT NULL,
    surname  TEXT NOT NULL,
    active   BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (forename, surname)
);

INSERT INTO umpires (forename, surname) VALUES
  ('Abrar',            'Ahmad'),
  ('Bashir',           'Ahmed'),
  ('Shahid',           'Ahmed'),
  ('Mohammed Ali',     'Akber'),
  ('Salman',           'Akhtar'),
  ('Adeel',            'Arif'),
  ('Martin',           'Ashfield'),
  ('Parth',            'Banerji'),
  ('David',            'Bardsley'),
  ('Michael',          'Beech'),
  ('Paul',             'Belston'),
  ('Dave',             'Bridge'),
  ('Mark',             'Brookes'),
  ('Steven',           'Burston'),
  ('Neil',             'Cadd'),
  ('Paul',             'Carter'),
  ('David',            'Chaloner'),
  ('Malcolm',          'Chapman'),
  ('Ahad (Mohammed)',  'Chowdhury'),
  ('James',            'Clarke'),
  ('Stephen',          'Coulding'),
  ('Stevie',           'Coulding'),
  ('David',            'Cowburn'),
  ('Brian',            'Crook'),
  ('Lee',              'Cullen'),
  ('Stephen',          'Cullen'),
  ('Stewart',          'Dobson'),
  ('Stephen',          'Draper'),
  ('Mike',             'Dunkerley'),
  ('Peter',            'Edwards'),
  ('David',            'Faulkner'),
  ('Billy',            'Fish'),
  ('Thomas',           'George'),
  ('Linval',           'Grant'),
  ('Mike',             'Grimes'),
  ('Jonathan',         'Grosskopf'),
  ('Damian',           'Grundy'),
  ('Edward',           'Haddon'),
  ('Lee',              'Harding'),
  ('Ian',              'Herbert'),
  ('Paul',             'Higgins'),
  ('Mike',             'Hill'),
  ('Matt',             'Hilton'),
  ('Mick',             'Holden'),
  ('Richard',          'Hope'),
  ('John',             'Howard'),
  ('Darren',           'Howarth'),
  ('John',             'Hughes'),
  ('Sarfraz',          'Ismail Ahmad'),
  ('Ashraf',           'Jamal'),
  ('James',            'Jones'),
  ('Ken',              'Jones'),
  ('Jayprakash',       'Joshi'),
  ('Ramki',            'Kalyanasundaram'),
  ('Melissa',          'Kay'),
  ('Stephen',          'Kenyon'),
  ('Mark',             'Keogh'),
  ('Anwar',            'Khan'),
  ('Behzad',           'Khan'),
  ('Stephen',          'Kirkbright'),
  ('Raja',             'Latif'),
  ('Fred',             'Leatherbarrow'),
  ('Asif',             'Lohdi'),
  ('Bobby',            'Loomba'),
  ('Peter',            'Masters'),
  ('Jon',              'Mayor'),
  ('Peter',            'McAndrew'),
  ('Billy',            'McEwen'),
  ('Arsalaan',         'Mohammad'),
  ('Abdul',            'Motala'),
  ('Farrukh',          'Munir'),
  ('Alan',             'Naylor'),
  ('Amrat',            'Patel'),
  ('Sarang',           'Pulikkal'),
  ('Kamlesh',          'Rajput'),
  ('Craig',            'Ramadhin'),
  ('Suhail',           'Rana'),
  ('Mahmood',          'Rather'),
  ('Roger',            'Richards'),
  ('Phil',             'Royle'),
  ('Stuart',           'Russell'),
  ('Mahammed Arshad',  'Saiyed'),
  ('Keith',            'Scholes'),
  ('Wilf',             'Seville'),
  ('Muhammad',         'Shahid'),
  ('Sardar',           'Shahid'),
  ('John',             'Sharples'),
  ('Neil',             'Shaw'),
  ('Zohaib',           'Shazad'),
  ('Ian',              'Standing'),
  ('Ian',              'Stobbs'),
  ('Nigel',            'Stock'),
  ('Bhikhu',           'Sukha'),
  ('John',             'Sumner'),
  ('Bernard',          'Sweeney'),
  ('Brian',            'Talbot'),
  ('Peter',            'Thew'),
  ('Denver',           'Thornton'),
  ('Amin',             'Tufail'),
  ('Mike',             'Tyldesley'),
  ('Richard',          'Unwin'),
  ('Steve',            'Ward'),
  ('Dave',             'Wild'),
  ('Steve',            'Wilkinson'),
  ('Alan',             'Wilson'),
  ('Beverley',         'Wilson'),
  ('Philip',           'Yates'),
  ('Fiz',              'Yousaf'),
  ('Shah',             'Zeb')
ON CONFLICT (forename, surname) DO NOTHING;
